name: CardForge CI/CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  android:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission
      run: chmod +x gradlew


    - name: Build project
      run: ./gradlew build --stacktrace

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest


    - name: Run Emulator Tests
      if: github.ref == 'refs/heads/main'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        arch: x86_64
        target: google_apis
        profile: pixel_6
        script: ./gradlew connectedCheck

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: CardForge-debug
        path: app/build/outputs/apk/debug/app-debug.apk